"""
core/lawyer_kit.py

Generates the "Ask a Lawyer" Prep Kit: a structured, chronological brief
that aggregates the risk analysis and any Q&A history into something a
user can print or export before meeting an attorney.
"""

from __future__ import annotations

import json
import re
from datetime import datetime

from pydantic import BaseModel, Field, ValidationError

from core_analyzer import RiskRadarResult
from core_config import get_chat_model
from core_prompts import LAWYER_PREP_PROMPT


class TimelineItem(BaseModel):
    date_or_stage: str = ""
    event: str = ""


class ConcernItem(BaseModel):
    concern: str = ""
    why_it_matters: str = ""
    priority: str = "Medium"


class LawyerPrepKit(BaseModel):
    document_overview: str = ""
    chronological_timeline: list[TimelineItem] = Field(default_factory=list)
    top_concerns: list[ConcernItem] = Field(default_factory=list)
    questions_for_attorney: list[str] = Field(default_factory=list)
    user_questions_asked: list[str] = Field(default_factory=list)


class LawyerKitError(Exception):
    pass


def _extract_json(raw_text: str) -> dict:
    text = raw_text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    first_brace = text.find("{")
    last_brace = text.rfind("}")
    if first_brace != -1 and last_brace != -1 and last_brace > first_brace:
        text = text[first_brace : last_brace + 1]
    return json.loads(text)


def generate_lawyer_prep_kit(
    risk_analysis: RiskRadarResult, qa_history: list[tuple[str, str]] | None = None
) -> LawyerPrepKit:
    """
    Builds the structured prep kit from an existing risk analysis plus
    optional Q&A history (list of (question, answer) tuples the user asked
    during their session).
    """
    qa_history = qa_history or []
    qa_text = (
        "\n".join(f"Q: {q}\nA: {a}" for q, a in qa_history)
        if qa_history
        else "(No questions were asked during this session.)"
    )

    llm = get_chat_model(temperature=0.2)
    prompt = LAWYER_PREP_PROMPT.format(
        risk_analysis_json=risk_analysis.model_dump_json(indent=2),
        qa_history=qa_text,
    )

    last_error = None
    for attempt in range(2):
        try:
            response = llm.invoke(prompt)
            parsed = _extract_json(response.content or "")
            return LawyerPrepKit(**parsed)
        except (json.JSONDecodeError, ValidationError, AttributeError) as e:
            last_error = e
            if attempt == 0:
                prompt += "\n\nIMPORTANT: Return ONLY the JSON object, no markdown fences."
                continue
        except Exception as e:
            raise LawyerKitError(f"Couldn't generate the prep kit: {e}") from e

    raise LawyerKitError(
        "The prep-kit model returned data that couldn't be parsed after "
        f"retrying ({last_error.__class__.__name__}). Please try again."
    )


def export_prep_kit_as_markdown(kit: LawyerPrepKit, document_name: str = "Document") -> str:
    """Renders the prep kit as a clean, printable Markdown document."""
    lines = []
    lines.append(f"# Ask-a-Lawyer Prep Kit — {document_name}")
    lines.append(f"_Generated by ClauseShield on {datetime.now().strftime('%Y-%m-%d %H:%M')}_")
    lines.append("")
    lines.append(
        "> ⚠️ This brief is AI-generated informational guidance, not legal "
        "advice. Review it with a licensed attorney before acting on it."
    )
    lines.append("")

    lines.append("## Document Overview")
    lines.append(kit.document_overview or "_Not available._")
    lines.append("")

    lines.append("## Chronological Timeline")
    if kit.chronological_timeline:
        for item in kit.chronological_timeline:
            lines.append(f"- **{item.date_or_stage}** — {item.event}")
    else:
        lines.append("_No specific dates or stages identified._")
    lines.append("")

    lines.append("## Top Concerns (Priority Order)")
    if kit.top_concerns:
        for c in kit.top_concerns:
            lines.append(f"### [{c.priority}] {c.concern}")
            lines.append(c.why_it_matters)
            lines.append("")
    else:
        lines.append("_No major concerns identified._")
    lines.append("")

    lines.append("## Questions to Ask Your Attorney")
    if kit.questions_for_attorney:
        for i, q in enumerate(kit.questions_for_attorney, start=1):
            lines.append(f"{i}. {q}")
    else:
        lines.append("_No specific questions generated._")
    lines.append("")

    if kit.user_questions_asked:
        lines.append("## Questions You Already Asked ClauseShield")
        lines.append("_(For your attorney's context — these were already answered by AI and may not need to be repeated.)_")
        for q in kit.user_questions_asked:
            lines.append(f"- {q}")
        lines.append("")

    lines.append("---")
    lines.append("_This document was generated by ClauseShield, an AI legal-document "
                  "assistant. It is provided for informational purposes only and does "
                  "not constitute legal advice or create an attorney-client relationship._")

    return "\n".join(lines)
